namespace AdventOfCode2024.Tests;

public class Day4Tests
{
    public static TheoryData<string, int> XmasData =>
        new()
        {
            {
                """
                ....
                ....
                ....
                ....
                """,
                0
            },
            {
                """
                XMAS
                ....
                ....
                ....
                """,
                1
            },
            {
                """
                XMA.
                ....
                ....
                ....
                """,
                0
            },
            {
                """
                SAMX
                ....
                ....
                ....
                """,
                1
            },
            {
                """
                XMAS
                XMAS
                ....
                ....
                """,
                2
            },
            {
                """
                XMASXMAS
                ........
                ........
                ........
                ........
                ........
                ........
                """,
                2
            },
            {
                """
                SAMXSAMX
                ........
                ........
                ........
                ........
                ........
                ........
                """,
                2
            },
            {
                """
                XMASSAMX
                ........
                ........
                ........
                ........
                ........
                ........
                ........
                """,
                2
            },
            {
                """
                X...
                .M..
                ..A.
                ...S
                """,
                1
            },
            {
                """
                ...X
                ..M.
                .A..
                S...
                """,
                1
            },
            {
                """
                ...S
                ..A.
                .M..
                X...
                """,
                1
            },
            {
                """
                S...
                .A..
                ..M.
                ...X
                """,
                1
            },
            {
                """
                X..S
                .MA.
                .MA.
                X..S
                """,
                2
            },
            {
                """
                X...
                M...
                A...
                S...
                """,
                1
            },
            {
                """
                ...S
                ...A
                ...M
                ...X
                """,
                1
            },
            {
                """
                XMASAMX
                .......
                .......
                .......
                .......
                .......
                .......
                """,
                2
            },
            {
                """
                X......
                M......
                A......
                S......
                A......
                M......
                X......
                """,
                2
            },
            {
                """
                MMMSXXMASM
                MSAMXMSMSA
                AMXSXMAAMM
                MSAMASMSMX
                XMASAMXAMM
                XXAMMXXAMA
                SMSMSASXSS
                SAXAMASAAA
                MAMMMXMMMM
                MXMXAXMASX
                """,
                18
            },
            {
                File.ReadAllText("Day4.txt"), 2633
            }
        };

    [Theory]
    [MemberData(nameof(XmasData))]
    public void GetXmasCount(string input, int expected)
    {
        Assert.Equal(expected, Day4.GetXmasCount(input));
    }

    public static TheoryData<string, int> XShapedMasData => new()
    {
        {
            """
            M.S
            .A.
            M.S
            """,
            1
        },
        {
            """
            S.S
            .A.
            M.M
            """,
            1
        },
        {
            """
            S.M
            .A.
            S.M
            """,
            1
        },
        {
            """
            M.M
            .A.
            S.S
            """,
            1
        },
        {
            """
            MMMSXXMASM
            MSAMXMSMSA
            AMXSXMAAMM
            MSAMASMSMX
            XMASAMXAMM
            XXAMMXXAMA
            SMSMSASXSS
            SAXAMASAAA
            MAMMMXMMMM
            MXMXAXMASX
            """,
            9
        },
        {
            File.ReadAllText("Day4.txt"), 1936
        }
    };

    [Theory]
    [MemberData(nameof(XShapedMasData))]
    public void GetXShapedMasCount(string input, int expected)
    {
        Assert.Equal(expected, Day4.GetXShapedMasCount(input));
    }
}